# Generated by Django 4.0.5 on 2022-12-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
